name: go_from_dart
publish_to: none
description: Sums two numbers with native code.
version: 0.1.0
repository: https://github.com/dart-lang/native/tree/main/pkgs/native_assets_cli/example/build/native_add_library

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
