name: dart_ffigen
version: 0.0.1
description: Example on how to make a hello world with ffigen
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.9.0

dev_dependencies:
  ffigen: ^14.0.0
